// ===== Quiz Data — History questions used when dice roll = 7 =====
// 小学校高学年〜中学生向けの世界史/日本史クイズ。
// 戦略ゲームに合うテーマ（資源・交易・帝国・文明）を中心に構成。

import type { QuizQuestion } from './gameTypes';

export const QUIZ_DATA: QuizQuestion[] = [
  // ---- かんたん ----
  {
    id: 'q-easy-1',
    question: '世界で初めて紙を発明したと言われている国はどこ？',
    options: ['日本', '中国', 'エジプト', 'イタリア'],
    correctIndex: 1,
    explanation: '紙は2世紀ごろ、中国の蔡倫（さいりん）が改良したと言われているよ。',
    difficulty: 'easy',
  },
  {
    id: 'q-easy-2',
    question: 'ピラミッドが作られた古代の国はどこ？',
    options: ['ギリシャ', 'ローマ', 'エジプト', 'インド'],
    correctIndex: 2,
    explanation: 'ピラミッドは古代エジプトで王（ファラオ）のお墓として作られたよ。',
    difficulty: 'easy',
  },
  {
    id: 'q-easy-3',
    question: '日本で初めて作られた都はどこ？',
    options: ['平城京', '平安京', '藤原京', '鎌倉'],
    correctIndex: 2,
    explanation: '694年に完成した藤原京が、日本で最初の本格的な都だよ。',
    difficulty: 'easy',
  },
  {
    id: 'q-easy-4',
    question: 'シルクロードで運ばれた主な品物は？',
    options: ['お米', '絹（シルク）', '石炭', 'ガラス'],
    correctIndex: 1,
    explanation: 'シルクロードはその名の通り、絹を東西で取引する交易路だったよ。',
    difficulty: 'easy',
  },
  {
    id: 'q-easy-5',
    question: 'コロンブスがたどり着いた大陸はどこ？',
    options: ['アフリカ', 'アメリカ', 'オーストラリア', '南極'],
    correctIndex: 1,
    explanation: '1492年、コロンブスは大西洋を渡ってアメリカ大陸に到達したよ。',
    difficulty: 'easy',
  },
  {
    id: 'q-easy-6',
    question: '日本で「鎖国」を行った時代はいつ？',
    options: ['平安時代', '鎌倉時代', '江戸時代', '明治時代'],
    correctIndex: 2,
    explanation: '江戸時代、幕府は外国との交流を制限する「鎖国」を行ったよ。',
    difficulty: 'easy',
  },
  {
    id: 'q-easy-7',
    question: '万里の長城がある国はどこ？',
    options: ['日本', '韓国', 'インド', '中国'],
    correctIndex: 3,
    explanation: '万里の長城は中国にあって、北方からの攻撃を防ぐために作られたよ。',
    difficulty: 'easy',
  },
  {
    id: 'q-easy-8',
    question: '産業革命が最初に起こった国はどこ？',
    options: ['フランス', 'ドイツ', 'イギリス', 'アメリカ'],
    correctIndex: 2,
    explanation: '18世紀のイギリスで蒸気機関などが生まれて産業革命が始まったよ。',
    difficulty: 'easy',
  },

  // ---- ふつう ----
  {
    id: 'q-norm-1',
    question: '日本に鉄砲を伝えたのはどの国の人？',
    options: ['ポルトガル', 'スペイン', 'オランダ', 'イギリス'],
    correctIndex: 0,
    explanation: '1543年、種子島に流れ着いたポルトガル人が鉄砲を伝えたよ。',
    difficulty: 'normal',
  },
  {
    id: 'q-norm-2',
    question: '世界で初めての石油の油田が発見された国は？',
    options: ['アメリカ', 'サウジアラビア', 'ロシア', 'イラン'],
    correctIndex: 0,
    explanation: '1859年、アメリカのペンシルベニア州で世界初の油田が掘られたよ。',
    difficulty: 'normal',
  },
  {
    id: 'q-norm-3',
    question: 'ローマ帝国の最盛期に使われていた共通の言葉は？',
    options: ['ギリシャ語', 'ラテン語', 'アラビア語', 'フランス語'],
    correctIndex: 1,
    explanation: 'ラテン語はローマ帝国の公用語で、今のヨーロッパの言葉のもとになったよ。',
    difficulty: 'normal',
  },
  {
    id: 'q-norm-4',
    question: '古代インカ帝国があった現在の国はどこ？',
    options: ['メキシコ', 'ペルー', 'ブラジル', 'チリ'],
    correctIndex: 1,
    explanation: 'インカ帝国は今のペルーを中心に栄えた、南アメリカ最大の帝国だよ。',
    difficulty: 'normal',
  },
  {
    id: 'q-norm-5',
    question: 'モンゴル帝国を築いた人物は誰？',
    options: ['フビライ・ハン', 'チンギス・ハン', 'マルコ・ポーロ', '織田信長'],
    correctIndex: 1,
    explanation: '13世紀、チンギス・ハンが遊牧民をまとめてユーラシア大陸を支配したよ。',
    difficulty: 'normal',
  },
  {
    id: 'q-norm-6',
    question: '「金閣寺」を建てた室町幕府の将軍は誰？',
    options: ['足利尊氏', '足利義満', '足利義政', '徳川家康'],
    correctIndex: 1,
    explanation: '3代将軍の足利義満が、京都に金閣寺（鹿苑寺）を建てたよ。',
    difficulty: 'normal',
  },
  {
    id: 'q-norm-7',
    question: 'フランス革命が始まった年は？',
    options: ['1689年', '1776年', '1789年', '1889年'],
    correctIndex: 2,
    explanation: '1789年、バスティーユ襲撃をきっかけにフランス革命が始まったよ。',
    difficulty: 'normal',
  },
  {
    id: 'q-norm-8',
    question: '日本で最も古いお金（貨幣）と言われているのは？',
    options: ['和同開珎', '富本銭', '天保通宝', '寛永通宝'],
    correctIndex: 1,
    explanation: '富本銭は7世紀に作られた日本最古の貨幣と考えられているよ。',
    difficulty: 'normal',
  },

  // ---- むずかしい ----
  {
    id: 'q-hard-1',
    question: '大航海時代、香辛料を求めてヨーロッパ人が向かったのはどこ？',
    options: ['アフリカ', 'インド・東南アジア', 'アメリカ', '北極'],
    correctIndex: 1,
    explanation: 'こしょうやナツメグなどの香辛料はインドや東南アジアでしか手に入らず、貴重な交易品だったよ。',
    difficulty: 'hard',
  },
  {
    id: 'q-hard-2',
    question: '世界三大宗教ではないのは次のうちどれ？',
    options: ['キリスト教', 'イスラム教', 'ヒンドゥー教', '仏教'],
    correctIndex: 2,
    explanation: '世界三大宗教はキリスト教・イスラム教・仏教。ヒンドゥー教は信者が多いけどインドが中心だよ。',
    difficulty: 'hard',
  },
  {
    id: 'q-hard-3',
    question: '産業革命で蒸気機関を改良した人物は？',
    options: ['エジソン', 'ジェームズ・ワット', 'ニュートン', 'ライト兄弟'],
    correctIndex: 1,
    explanation: 'ジェームズ・ワットが18世紀に蒸気機関を改良し、工業生産を大きく変えたよ。',
    difficulty: 'hard',
  },
  {
    id: 'q-hard-4',
    question: '第一次世界大戦のきっかけとなった事件は？',
    options: ['真珠湾攻撃', 'サラエボ事件', 'ロシア革命', '日露戦争'],
    correctIndex: 1,
    explanation: '1914年、サラエボでオーストリア皇太子が暗殺されたことが第一次世界大戦のきっかけだよ。',
    difficulty: 'hard',
  },
  {
    id: 'q-hard-5',
    question: '日本が初めて参加したオリンピックの開催地は？',
    options: ['ロンドン', 'パリ', 'ストックホルム', 'ベルリン'],
    correctIndex: 2,
    explanation: '1912年のストックホルム大会に、日本は初めて選手を派遣したよ。',
    difficulty: 'hard',
  },
  {
    id: 'q-hard-6',
    question: 'アメリカ独立宣言が発表された年は？',
    options: ['1492年', '1776年', '1789年', '1812年'],
    correctIndex: 1,
    explanation: '1776年7月4日、アメリカは13植民地としてイギリスからの独立を宣言したよ。',
    difficulty: 'hard',
  },
  {
    id: 'q-hard-7',
    question: '古代エジプト文明はどの川のほとりで栄えた？',
    options: ['チグリス川', 'インダス川', 'ナイル川', '黄河'],
    correctIndex: 2,
    explanation: 'ナイル川の氾濫がもたらす肥えた土で農業が発達し、エジプト文明が栄えたよ。',
    difficulty: 'hard',
  },
  {
    id: 'q-hard-8',
    question: '明治時代、日本が初めて結んだ不平等条約の相手は？',
    options: ['イギリス', 'ロシア', 'アメリカ', '中国'],
    correctIndex: 2,
    explanation: '1858年の日米修好通商条約で、日本は関税自主権がない不平等な条約を結んだよ。',
    difficulty: 'hard',
  },
];
